### ISSUE TITLE
Connectivity between Package Explorer and AASX Server

### ISSUE THREAD

**Issue by JoMMC** [admin-shell-io/aasx-server#63]
Hello, it is possible to build up a connection from the Package Explorer to the AASX Server to add further AAS into the designated directory. Which kind of connection does work for this? Is there a documentation available?
Thanks

**Comment by juileetikekar** [comment]
@JoMMC and @imcardle : Thank you for your inputs. We are working on the REST API for uploading a new file to the AASX- Server from the Package Explorer. The fix will be released soon.

**Comment by juileetikekar** [comment]
This issue has been fixed in the new REST API support with ASP.NET.
The new REST endpoint is : http://<Host>:5001/
Swagger documentation for these APIs can be found at : http://<Host>:5001/swagger/index.html
Package explorer can be connected to Aasx-Server by: File -> AASX File Repository -> Connect HTTP/REST Repository and appending "?asp.net" to the new REST endoint as shown in the screenshot.

![image](https://user-images.githubusercontent.com/99317579/165459724-ecb28d8e-2205-4ae2-9790-c050ab30b592.png)
