### ISSUE TITLE
Return actual AASX file when downloading via GET /server/getaasx/{ID}

### ISSUE THREAD

**Issue by jankoh** [admin-shell-io/aasx-server#75]
Hi,

while testing the download feature of the REST server part, I figured the aasx file is somehow rebuilt for download. At least the xml part is rewritten.

This will fail, if a signed aasx file is downloaded, since the signature verification of the downloaded file will most likely fail (except for the case the rebuilt xml matches *exactly* the original one). Also, it simply seems odd the downloaded file does not match the original one.

I suggest, the download endpoint should just take the aasx file from the input folder and send it to the client *as is*.

**Comment by juileetikekar** [comment]
@jankoh Thank you for your inputs. We are working on it and the fix will be realeased soon.

**Comment by juileetikekar** [comment]
This issue has been fixed in the new REST API support with ASP.NET.
The new REST endpoint is : http:// <Host_Name> :5001/
Swagger documentation for these APIs can be found at : http://<Host_Name>:5001/swagger/index.html
Package explorer can be connected to Aasx-Server by: File -> AASX File Repository -> Connect HTTP/REST Repository and appending "?asp.net" to the new REST endoint as shown in the screenshot.

![image](https://user-images.githubusercontent.com/99317579/165459724-ecb28d8e-2205-4ae2-9790-c050ab30b592.png)
